# 1 넘파이 배열

* ndarray 생성 np.array()

In [1]:
import numpy as np #일단 넘파이 모듈은 관습상 np라는 이름으로 축약해줍니다! 

In [2]:
list1 = [1, 2, 3] #리스트를 만들어주고 
print("list1:",list1)
print("list1 type:",type(list1)) # list

array1 = np.array(list1) # ndarray 안에 리스트 인자로! 
print("array1:",array1)
print("array1 type:", type(array1)) # ndarray

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray 의 형태(shape)와 차원

In [3]:
array1 = np.array([1,2,3]) # 1차원 ndarray
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape) # 형태 알아보기 

array2 = np.array([[1,2,3],
                  [2,3,4]]) # 2차원 
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape) # 형태알아보기 

array3 = np.array([[1,2,3]]) #2차원 
print('array3 type:',type(array3)) 
print('array3 array 형태:',array3.shape) #형태 알아보기 

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
#차원 알아보기! 

array1: 1차원, array2: 2차원, array3:  2차원


* ndarray  데이터 값 타입

In [5]:
list1 = [1,2,3]
print(type(list1)) #list 
array1 = np.array(list1) 

print(type(array1))# ndarray
print(array1, array1.dtype) # 데이터 타입 알아보기 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
# 데이터 값의 타입이 다르다?!!? 

list2 = [1, 2, 'test'] # 리스트는 가능 
array2 = np.array(list2)
print(array2, array2.dtype) 
# ndarray는 안 됨! 이렇게 되면 정수형 값들이 크기가 더 큰 문자열 타입으로 변한다 

list3 = [1, 2, 3.0] # 리스트는 가능
array3 = np.array(list3)
print(array3, array3.dtype) 
# 정수형 값들이 모두 실수로 변함

['1' '2' 'test'] <U11
[1. 2. 3.] float64


* astype()을 통한 타입 변환 

In [7]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # 64bit 실수형으로 변환해주세요! 
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32') #32bit 정수형으로 변환!
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32') 
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


* ndarray에서 axis 기반의 연산함수 수행

In [8]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum()) # 전체를 다 더해라 
print(array2.sum(axis=0)) 
# axis 0 방향 == 행방향(행의 개수를 셀 수 있는 방향) == 아래로  더해라! 
# 행으로 나누고 더해봐라
print(array2.sum(axis=1)) 
# axis 1 방향 == 열 방향(열의 개수를 셀 수 있는 방향) == 옆으로 다 더해라 

15
[3 5 7]
[6 9]


## 2. ndarray와 관련된 함수덜

**ndarray를 편리하게 생성하기 - arange, zeros, ones** 

In [9]:
sequence_array = np.arange(10) # 연속된 ndarray 초기화! 
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [10]:
zero_array = np.zeros((3,2),dtype='int32') # 모두 0으로 초기화 
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) #모두 1로 초기화 
print(one_array)
print(one_array.dtype, one_array.shape) #실수형으로 나온다는 거 주의!

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


**ndarray의 shape를 변경하는 reshape()**

In [11]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) # 이렇게 shpae() 변환! 
print('array2:\n',array2)

array3 = array1.reshape(5,2) #이렇게 shape() 변환
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
# 변환할 수 있는 shape구조를 입력하면 오류 발생.
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

### 2-1. reshape(-1) 완전정복

**reshape()의 -1이 의미 : 변경된 배열의 -1 위치의 차원은 "원래 배열의 길이와 남은 차원으로부터 추정" 된다는 걸 의미합니다!**

In [13]:
x = np.arange(12) # 넘파이 배열 만들어주자~
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

* reshape(-1,정수) : 행의 위치에 -1인 경우 / 열의 값은 지정해준대로, 변환될 배열의 행의 수는 알아서 지정

In [14]:
# 즉 열의 크기는 1로 고정하고 행의 크기는 자동으로 변환 해라! 즉 12X1의 형태로 변환
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [15]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

* reshape(-1)인 경우

In [17]:
x.reshape(-1) # 1차원 배열을 반환! 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
x.reshape(1,-1) #1차원 배열처럼 보이지만 이는 (1,12)인 2차원 배열임!! 대괄호 수를 봐봐!

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

* -1 을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생.

In [5]:
import numpy as np #일단 넘파이 모듈은 관습상 np라는 이름으로 축약해줍니다! 

In [6]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) 
#10개의 요소를 가진 배열을 열의 크기가 4인 2차원 배열을 만들 수 없다..
# 꽉꽉 채워지지 않자나!!

ValueError: cannot reshape array of size 10 into shape (4)

* 반드시 -1 값은 1개의 인자만 입력해야 함

In [1]:
array1.reshape(-1, -1) # 모두가 불확정이기 때문에 어떻게 바뀌는지 알 수가 없잖아!!

NameError: name 'array1' is not defined

## RETURN 2. ndarray와 관련된 함수덜

**ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)** 

* 특정 위치의 단일값 추출 

In [7]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2] # 특정 값 추출
print('value:',value) 
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [8]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2]) # 인덱스가 -일때

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [9]:
# 업데이트 하는 것! 
array1[0] = 9 
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [10]:
#다차원일 때!
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* 슬라이싱(Slicing)

In [11]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3] # 슬라이싱 
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 인덱스에 아무것도 없으면 끝 부분을 의미
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [13]:
# 다차원에서도 슬라이싱 가능
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


* 팬시 인덱싱(fancy indexing)

In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2] # 행축의 0과1 인덱스 열축의 2 인덱스 가져와라
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,2], 0:2] #행으로 팬시 인덱싱 열축으로 슬라이싱 했음! 
print('array2d[[0,2], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]] # 열축으로 아무것도 없으니까 모두 해당!  
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,2], 0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* 불린 인덱싱(Boolean indexing)

In [15]:
# 1차원 배열을 만들고
array1d = np.arange(start=1, stop=10)
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [16]:
print(array1d > 5) # 이 조건식만 쓰면 각각의 요소가 조건에 대한 True False가 나옴

var1 = array1d > 5
print("var1:",var1)
print(type(var1))

[False False False False False  True  True  True  True]
var1: [False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [17]:
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
print(array1d)
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [20]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
# 기존의 배열에 불린 값을 주고 
array3 = array1d[boolean_indexes] #불린 인덱싱을 해보면 
print('불린 인덱스로 필터링 결과 :', array3) #true인 애들만 필털이하게 됨!
#즉 []안에 조건식을 써주고 True인 애들만의 값들이 출력하게 된다!  

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [22]:
indexes = np.array([5,6,7,8]) # 5번째 6번째 7번째 8 번째 인덱스만 팬시 인덱싱으로 넣어주고
array4 = array1d[ indexes ] # [] 안에 indexes만 넣어주면 값이 나옵니다1 아 디폴트가 True라는 것을 알 수 있다 
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [23]:
# 이렇게 복잡하게 쓸거야.. 
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [25]:
#아니면 이렇게 간단하게 쓸거야.
print(array1d[array1 > 5])

[6 7 8 9]


즉 메카니즘을 보면 
1. array1d가 5보다 큰지 boolean 조건이 있음
2. bool 값을 갖는 ndarrayr가 만들어짐! 이때 False 값은 무시하고 이때 Flase ㄱ밧은 무시하고 True 값에 해당하는 index 값만 저장됨! 

**배열의 정렬 - sort()와 argsort()**

* 배열 정렬 - sort()

In [27]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 배열:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 배열:', sort_array1) 
print('np.sort( ) 호출 후 원본 배열:', org_array) #원본 행렬 확인! 

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
org_array.sort()
print('org_array.sort( ) 호출 후 반환된 배열:', sort_array2)
print('org_array.sort( ) 호출 후 원본 배열:', org_array)

원본 배열: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 배열: [1 3 5 9]
np.sort( ) 호출 후 원본 배열: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 배열: None
org_array.sort( ) 호출 후 원본 배열: [1 3 5 9]


In [28]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [29]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0) #행방향으로 정렬 
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) #열방향으로 정렬 
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


* 배열 정렬 - argsort()

In [30]:
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)) # 정렬된 값이 출력되는 반면

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('배열 정렬 시 원본 배열의 인덱스:', sort_indices) # 정렬된 값의 원본 인덱스가 반환

[1 3 5 9]
<class 'numpy.ndarray'>
배열 정렬 시 원본 배열의 인덱스: [1 0 3 2]


In [31]:
#내림차순
org_array = np.array([ 3, 1, 9, 5]) 
print(np.sort(org_array)[::-1])

sort_indices_desc = np.argsort(org_array)[::-1]
print('배열 내림차순 정렬 시 원본 배열의 인덱스:', sort_indices_desc)

[9 5 3 1]
배열 내림차순 정렬 시 원본 배열의 인덱스: [2 3 0 1]


key-value 형태의 데이터를 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 만들고 argsort()를 이용하여 key값을 정렬하고자 합니다! 

In [32]:
# 암묵적으로 Mapping이 되었다고 생각! 
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel']) # 이름 배열 
score_array=np.array([78, 95, 84, 98, 88]) # 점수 배열 

#이때 낮은 점수를 가진 순서대로 사람들을 출력해보고 싶다! 
# score_array의 정렬된 값에 해당하는 원본 배열 위치 인덱스 반환하고 이를 이용하여 name_array에서 name값 추출.  
sort_indices = np.argsort(score_array)
print("sort indices:", sort_indices) # 정렬된 값의 원본 인덱스 반환 

name_array_sort = name_array[sort_indices] # Name_array에 정렬된 값의 원본 인덱스 배열을 팬시 인덱싱 방식으로 데이터 셋 찾아줌! 

score_array_sort = score_array[sort_indices] # score_array에 팬시 인덱싱으로 찾아줌1
print(name_array_sort)
print(score_array_sort)

sort indices: [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

* 행렬 내적

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


* 전치 행렬

In [34]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
